# Generated by Django 5.2.8 on 2026-06-06 15:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('tipo', models.CharField(choices=[('PICOLE', 'Picole'), ('PALETA ', 'Paleta'), ('MORENINHA', 'Moreninha'), ('COBERTURA', 'Cobertura'), ('CASQUINHA', 'Casquinha'), ('CASCÃO', 'Cascão'), ('MELHORADO 300ML', 'Melhorado 300ml'), ('MELHORADO 500ML', 'Melhorado 500ml'), ('MELHORADO 1L', 'Melhorado 1l'), ('FONDUE PEQUENO', 'Fondue pequeno'), ('FONDUE GRANDE', 'Fondue grande'), ('AÇAI NO COPO 300ML', 'Açai no copo 300ml'), ('AÇAI NO COPO 400ML', 'Açai no copo 400ml'), ('AÇAI NO COPO 500ML', 'Açai no copo 500ml'), ('AÇAI NO COPO 700ML', 'Açai no copo 700ml'), ('POTE AÇAI 1L COM ACOMPANHAMENTOS', 'Pote açai 1l com companhamentos'), ('POTE AÇAI 2L COM ACOMPANHAMENTOS', 'Pote açai 2l com companhamentos'), ('POTE AÇAI 1L', 'Pote açai 1l'), ('POTE AÇAI 2L', 'Pote açai 2l'), ('POTE CUPUAÇU 1L', 'Pote cupuaçu 1l'), ('POTE SORVETE 1,5L', 'Pote sorvete 1,5l'), ('POTE SORVETE 2L', 'Pote sorvete 2l'), ('SKIMO', 'Skimo'), ('ÁGUA S/GÁS', 'Água s/gás'), ('ÁGUA C/GÁS', 'Água c/gás'), ('CESTINHA', 'Cestinha')], max_length=100)),
                ('quantidade', models.IntegerField()),
                ('preco_de_custo', models.DecimalField(decimal_places=2, max_digits=10)),
                ('preco_de_venda', models.DecimalField(decimal_places=2, max_digits=10)),
                ('estoque_minimo', models.IntegerField()),
                ('validade', models.DateTimeField(auto_now_add=True)),
                ('data_cadastro', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Movimentacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('ENTRADA', 'Entrada'), ('SAIDA', 'Saída')], max_length=10)),
                ('quantidade', models.IntegerField()),
                ('data_operacao', models.DateTimeField(auto_now_add=True)),
                ('responsavel', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimentacoes', to='api.produto')),
            ],
        ),
    ]
